choco install 7zip
choco install audacity
choco install avidemux
choco install blender
choco install cpu-z
choco install crystaldiskinfo
choco install discord
choco install docker
choco install epicgameslauncher
choco install foxitreader
choco install gimp
choco install handbrake
choco install libreoffice-fresh
choco install miktex
choco install mpc-hc
choco install notepadplusplus
choco install paint.net
choco install obs-studio
choco install qbittorrent
choco install retroarch
choco install sharex
choco install slack
choco install steam
choco install telegram
choco install texmaker
choco install vlc
choco install vscode
choco install windirstat
choco install zoom

:: Will have to install Blitz, League of Legends, Logitech Drivers, GPU Drivers, WSL 2, Ubuntu on WSL, Games, Voicemeeter, Google Drive manually
